[phases.setup]
nixPkgs = ["php84", "php84-pdo_mysql"]

[phases.build]
# This copies your local php.ini into the system path so PHP picks it up
cmds = ["cp php.ini /etc/php84/php.ini"]

[start]
cmd = "frankenphp run --config /app/Caddyfile"